### PR TITLE
Add support for reading repos default branch name when creating pull request

### LINKED ISSUE #11: Default branch might not be `master`
Currently, the script creates the pull requests to the `master` branch, but that might not be the default branch of the repository. Although this is uncommon, it does happens in few repositories where the default branch is `1.x`, `beta`, etc, and [possibly in the future](https://lore.kernel.org/git/nycvar.QRO.7.76.6.2006091126540.482@ZVAVAG-DN14RQO.ybpnyqbznva/), `main`.

When this does happen, the script either:
- fails, if there is no `master` branch,
- "works", but will be probably pushing to an abandoned `master` branch that is not meant to be default.

---

I tried to fix it by changing the "master" hardcoded strings on `script/modules/repo.ts` with [this](https://stackoverflow.com/a/50056710/7651928), but I'm afraid that this won't be enough, as there are other "master" occurrences on few `json` files (not sure if those must be replaced as well).

### PR DESCRIPTION
**Pull request by lucasecdb**
Fixes #11

### CODE REVIEW

**Comment by wdsrocha** [comment]
looks good :amaze:
have you tested it? If not, I guess I could run some (opening a PR to `portal-ui` and some random repo with `master` as default branch)

**Comment by lucasecdb** [comment]
I did not test it 😬 and was wandering on how to do that without opening a PR :-/

**Comment by wdsrocha** [comment]
> was wandering on how to do that without opening a PR :-/

Me too :^(. Well, at least we can test on repositories outside VTEX, if that helps

**Comment by lucasecdb** [comment]
@wdsrocha just tested it and created two pull-requests (one in admin-checkout and other in checkout-config-graphql) and it worked as expected :-)

**Comment by lucasecdb** [comment]
the prs created were:

- https://github.com/vtex/admin-checkout/pull/4
- https://github.com/vtex/checkout-config-graphql/pull/10

**Review by wdsrocha — APPROVED** [review]
good job!

**Pull request merged**
